const packageManagers = [
  { 'Programming Language': 'C', 'Equivalent File(s)': 'Makefile' },
  { 'Programming Language': 'C++', 'Equivalent File(s)': 'CMakeLists.txt' },
  {
    'Programming Language': 'C#',
    'Equivalent File(s)': 'project.json, packages.config (older versions), csproj (newer versions)',
  },
  { 'Programming Language': 'Clojure', 'Equivalent File(s)': 'deps.edn' },
  { 'Programming Language': 'CoffeeScript', 'Equivalent File(s)': 'package.json' },
  { 'Programming Language': 'Dart', 'Equivalent File(s)': 'pubspec.yaml' },
  { 'Programming Language': 'Elixir', 'Equivalent File(s)': 'mix.exs' },
  { 'Programming Language': 'Erlang', 'Equivalent File(s)': 'rebar.config' },
  { 'Programming Language': 'Go', 'Equivalent File(s)': 'go.mod, go.sum' },
  { 'Programming Language': 'Haskell', 'Equivalent File(s)': 'stack.yaml, cabal.config' },
  { 'Programming Language': 'Java', 'Equivalent File(s)': 'pom.xml (Maven), build.gradle (Gradle)' },
  { 'Programming Language': 'JavaScript (Back-end)', 'Equivalent File(s)': 'package.json' },
  { 'Programming Language': 'JavaScript (Front-end)', 'Equivalent File(s)': 'package.json' },
  { 'Programming Language': 'Kotlin', 'Equivalent File(s)': 'build.gradle.kts, build.gradle' },
  { 'Programming Language': 'Lua', 'Equivalent File(s)': 'rockspec' },
  {
    'Programming Language': '.NET',
    'Equivalent File(s)': 'project.json, packages.config (older versions), csproj (newer versions)',
  },
  { 'Programming Language': 'Objective-C', 'Equivalent File(s)': 'Podfile' },
  { 'Programming Language': 'Perl', 'Equivalent File(s)': 'META.json, META.yml, cpanfile' },
  { 'Programming Language': 'PHP', 'Equivalent File(s)': 'composer.json, composer.lock' },
  { 'Programming Language': 'Python', 'Equivalent File(s)': 'setup.py, requirements.txt, Pipfile, pyproject.toml' },
  { 'Programming Language': 'R', 'Equivalent File(s)': 'DESCRIPTION, NAMESPACE' },
  { 'Programming Language': 'Ruby', 'Equivalent File(s)': 'Gemfile, Gemfile.lock, Rakefile' },
  { 'Programming Language': 'Rust', 'Equivalent File(s)': 'Cargo.toml, Cargo.lock' },
  { 'Programming Language': 'Scala', 'Equivalent File(s)': 'build.sbt' },
  { 'Programming Language': 'Swift', 'Equivalent File(s)': 'Package.swift' },
  { 'Programming Language': 'TypeScript', 'Equivalent File(s)': 'package.json' },
];
